#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       :   # The title of the book. Will be placed in the left navbar.
author                      : Levi McClenny  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : images/logo.png  # A path to the book logo

html:
  favicon: images/tdq-profile.png
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true


repository:
  url: https://github.com/tensordiffeq/tdq-docs
  branch: master